/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteKennisRouteImport } from './routes/_site.kennis'
import { Route as SiteDienstenRouteImport } from './routes/_site.diensten'
import { Route as SiteDienstenIndexRouteImport } from './routes/_site.diensten.index'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKennisRoute = SiteKennisRouteImport.update({
  id: '/kennis',
  path: '/kennis',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDienstenRoute = SiteDienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDienstenIndexRoute = SiteDienstenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteDienstenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/diensten': typeof SiteDienstenRouteWithChildren
  '/kennis': typeof SiteKennisRoute
  '/diensten/': typeof SiteDienstenIndexRoute
}
export interface FileRoutesByTo {
  '/kennis': typeof SiteKennisRoute
  '/': typeof SiteIndexRoute
  '/diensten': typeof SiteDienstenIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/diensten': typeof SiteDienstenRouteWithChildren
  '/_site/kennis': typeof SiteKennisRoute
  '/_site/': typeof SiteIndexRoute
  '/_site/diensten/': typeof SiteDienstenIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/diensten' | '/kennis' | '/diensten/'
  fileRoutesByTo: FileRoutesByTo
  to: '/kennis' | '/' | '/diensten'
  id:
    | '__root__'
    | '/_site'
    | '/_site/diensten'
    | '/_site/kennis'
    | '/_site/'
    | '/_site/diensten/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kennis': {
      id: '/_site/kennis'
      path: '/kennis'
      fullPath: '/kennis'
      preLoaderRoute: typeof SiteKennisRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/diensten': {
      id: '/_site/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof SiteDienstenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/diensten/': {
      id: '/_site/diensten/'
      path: '/'
      fullPath: '/diensten/'
      preLoaderRoute: typeof SiteDienstenIndexRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
  }
}

interface SiteDienstenRouteChildren {
  SiteDienstenIndexRoute: typeof SiteDienstenIndexRoute
}

const SiteDienstenRouteChildren: SiteDienstenRouteChildren = {
  SiteDienstenIndexRoute: SiteDienstenIndexRoute,
}

const SiteDienstenRouteWithChildren = SiteDienstenRoute._addFileChildren(
  SiteDienstenRouteChildren,
)

interface SiteRouteChildren {
  SiteDienstenRoute: typeof SiteDienstenRouteWithChildren
  SiteKennisRoute: typeof SiteKennisRoute
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDienstenRoute: SiteDienstenRouteWithChildren,
  SiteKennisRoute: SiteKennisRoute,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
