/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SiteRouteImport } from './routes/_site'
import { Route as SiteIndexRouteImport } from './routes/_site.index'
import { Route as SiteKennisRouteImport } from './routes/_site.kennis'
import { Route as SiteDienstenRouteImport } from './routes/_site.diensten'
import { Route as SiteKennisIndexRouteImport } from './routes/_site.kennis.index'
import { Route as SiteDienstenIndexRouteImport } from './routes/_site.diensten.index'
import { Route as SiteDienstenSeoRouteImport } from './routes/_site.diensten.seo'
import { Route as SiteDienstenSeaRouteImport } from './routes/_site.diensten.sea'
import { Route as SiteDienstenGeoRouteImport } from './routes/_site.diensten.geo'
import { Route as SiteDienstenCroRouteImport } from './routes/_site.diensten.cro'

const SiteRoute = SiteRouteImport.update({
  id: '/_site',
  getParentRoute: () => rootRouteImport,
} as any)
const SiteIndexRoute = SiteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKennisRoute = SiteKennisRouteImport.update({
  id: '/kennis',
  path: '/kennis',
  getParentRoute: () => SiteRoute,
} as any)
const SiteDienstenRoute = SiteDienstenRouteImport.update({
  id: '/diensten',
  path: '/diensten',
  getParentRoute: () => SiteRoute,
} as any)
const SiteKennisIndexRoute = SiteKennisIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteKennisRoute,
} as any)
const SiteDienstenIndexRoute = SiteDienstenIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SiteDienstenRoute,
} as any)
const SiteDienstenSeoRoute = SiteDienstenSeoRouteImport.update({
  id: '/seo',
  path: '/seo',
  getParentRoute: () => SiteDienstenRoute,
} as any)
const SiteDienstenSeaRoute = SiteDienstenSeaRouteImport.update({
  id: '/sea',
  path: '/sea',
  getParentRoute: () => SiteDienstenRoute,
} as any)
const SiteDienstenGeoRoute = SiteDienstenGeoRouteImport.update({
  id: '/geo',
  path: '/geo',
  getParentRoute: () => SiteDienstenRoute,
} as any)
const SiteDienstenCroRoute = SiteDienstenCroRouteImport.update({
  id: '/cro',
  path: '/cro',
  getParentRoute: () => SiteDienstenRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof SiteIndexRoute
  '/diensten': typeof SiteDienstenRouteWithChildren
  '/kennis': typeof SiteKennisRouteWithChildren
  '/diensten/cro': typeof SiteDienstenCroRoute
  '/diensten/geo': typeof SiteDienstenGeoRoute
  '/diensten/sea': typeof SiteDienstenSeaRoute
  '/diensten/seo': typeof SiteDienstenSeoRoute
  '/diensten/': typeof SiteDienstenIndexRoute
  '/kennis/': typeof SiteKennisIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof SiteIndexRoute
  '/diensten/cro': typeof SiteDienstenCroRoute
  '/diensten/geo': typeof SiteDienstenGeoRoute
  '/diensten/sea': typeof SiteDienstenSeaRoute
  '/diensten/seo': typeof SiteDienstenSeoRoute
  '/diensten': typeof SiteDienstenIndexRoute
  '/kennis': typeof SiteKennisIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_site': typeof SiteRouteWithChildren
  '/_site/diensten': typeof SiteDienstenRouteWithChildren
  '/_site/kennis': typeof SiteKennisRouteWithChildren
  '/_site/': typeof SiteIndexRoute
  '/_site/diensten/cro': typeof SiteDienstenCroRoute
  '/_site/diensten/geo': typeof SiteDienstenGeoRoute
  '/_site/diensten/sea': typeof SiteDienstenSeaRoute
  '/_site/diensten/seo': typeof SiteDienstenSeoRoute
  '/_site/diensten/': typeof SiteDienstenIndexRoute
  '/_site/kennis/': typeof SiteKennisIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/diensten'
    | '/kennis'
    | '/diensten/cro'
    | '/diensten/geo'
    | '/diensten/sea'
    | '/diensten/seo'
    | '/diensten/'
    | '/kennis/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/diensten/cro'
    | '/diensten/geo'
    | '/diensten/sea'
    | '/diensten/seo'
    | '/diensten'
    | '/kennis'
  id:
    | '__root__'
    | '/_site'
    | '/_site/diensten'
    | '/_site/kennis'
    | '/_site/'
    | '/_site/diensten/cro'
    | '/_site/diensten/geo'
    | '/_site/diensten/sea'
    | '/_site/diensten/seo'
    | '/_site/diensten/'
    | '/_site/kennis/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  SiteRoute: typeof SiteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_site': {
      id: '/_site'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof SiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_site/': {
      id: '/_site/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof SiteIndexRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kennis': {
      id: '/_site/kennis'
      path: '/kennis'
      fullPath: '/kennis'
      preLoaderRoute: typeof SiteKennisRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/diensten': {
      id: '/_site/diensten'
      path: '/diensten'
      fullPath: '/diensten'
      preLoaderRoute: typeof SiteDienstenRouteImport
      parentRoute: typeof SiteRoute
    }
    '/_site/kennis/': {
      id: '/_site/kennis/'
      path: '/'
      fullPath: '/kennis/'
      preLoaderRoute: typeof SiteKennisIndexRouteImport
      parentRoute: typeof SiteKennisRoute
    }
    '/_site/diensten/': {
      id: '/_site/diensten/'
      path: '/'
      fullPath: '/diensten/'
      preLoaderRoute: typeof SiteDienstenIndexRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
    '/_site/diensten/seo': {
      id: '/_site/diensten/seo'
      path: '/seo'
      fullPath: '/diensten/seo'
      preLoaderRoute: typeof SiteDienstenSeoRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
    '/_site/diensten/sea': {
      id: '/_site/diensten/sea'
      path: '/sea'
      fullPath: '/diensten/sea'
      preLoaderRoute: typeof SiteDienstenSeaRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
    '/_site/diensten/geo': {
      id: '/_site/diensten/geo'
      path: '/geo'
      fullPath: '/diensten/geo'
      preLoaderRoute: typeof SiteDienstenGeoRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
    '/_site/diensten/cro': {
      id: '/_site/diensten/cro'
      path: '/cro'
      fullPath: '/diensten/cro'
      preLoaderRoute: typeof SiteDienstenCroRouteImport
      parentRoute: typeof SiteDienstenRoute
    }
  }
}

interface SiteDienstenRouteChildren {
  SiteDienstenCroRoute: typeof SiteDienstenCroRoute
  SiteDienstenGeoRoute: typeof SiteDienstenGeoRoute
  SiteDienstenSeaRoute: typeof SiteDienstenSeaRoute
  SiteDienstenSeoRoute: typeof SiteDienstenSeoRoute
  SiteDienstenIndexRoute: typeof SiteDienstenIndexRoute
}

const SiteDienstenRouteChildren: SiteDienstenRouteChildren = {
  SiteDienstenCroRoute: SiteDienstenCroRoute,
  SiteDienstenGeoRoute: SiteDienstenGeoRoute,
  SiteDienstenSeaRoute: SiteDienstenSeaRoute,
  SiteDienstenSeoRoute: SiteDienstenSeoRoute,
  SiteDienstenIndexRoute: SiteDienstenIndexRoute,
}

const SiteDienstenRouteWithChildren = SiteDienstenRoute._addFileChildren(
  SiteDienstenRouteChildren,
)

interface SiteKennisRouteChildren {
  SiteKennisIndexRoute: typeof SiteKennisIndexRoute
}

const SiteKennisRouteChildren: SiteKennisRouteChildren = {
  SiteKennisIndexRoute: SiteKennisIndexRoute,
}

const SiteKennisRouteWithChildren = SiteKennisRoute._addFileChildren(
  SiteKennisRouteChildren,
)

interface SiteRouteChildren {
  SiteDienstenRoute: typeof SiteDienstenRouteWithChildren
  SiteKennisRoute: typeof SiteKennisRouteWithChildren
  SiteIndexRoute: typeof SiteIndexRoute
}

const SiteRouteChildren: SiteRouteChildren = {
  SiteDienstenRoute: SiteDienstenRouteWithChildren,
  SiteKennisRoute: SiteKennisRouteWithChildren,
  SiteIndexRoute: SiteIndexRoute,
}

const SiteRouteWithChildren = SiteRoute._addFileChildren(SiteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  SiteRoute: SiteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
